/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClipCard: typeof import('./components/ClipCard.vue')['default']
    ClipDetailPanel: typeof import('./components/ClipDetailPanel.vue')['default']
    HistoryRestoreModal: typeof import('./components/HistoryRestoreModal.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PreviewThumb: typeof import('./components/PreviewThumb.vue')['default']
    PromptDiffModal: typeof import('./components/PromptDiffModal.vue')['default']
    PromptEditor: typeof import('./components/PromptEditor.vue')['default']
    PromptHistoryPanel: typeof import('./components/PromptHistoryPanel.vue')['default']
    RefGrid: typeof import('./components/RefGrid.vue')['default']
    ResolutionParam: typeof import('./components/ResolutionParam.vue')['default']
    Timeline: typeof import('./components/Timeline.vue')['default']
    TimelineRuler: typeof import('./components/TimelineRuler.vue')['default']
    TimelineTrack: typeof import('./components/TimelineTrack.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    UploadSlot: typeof import('./components/UploadSlot.vue')['default']
  }
}
